package com.openclassrooms.magicgithub.api;

import com.openclassrooms.magicgithub.model.User;
import java.util.List;
import java.util.Random;

import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.FAKE_USERS_RANDOM;
import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.generateUsers;

public class FakeApiService implements ApiService {
    Random randomUser = new Random();
    private List<User> users = generateUsers();
    // Implemented methods to generate action from the API to return to the mobile app user.
    /**
     * Return a list of {@link User}
     * Those users must be generated by {@link FakeApiServiceGenerator}
     */
    @Override
    public List<User> getUsers() {
        // TODO: A modifier
        return users;
        // users equals generateUsers() in FakeApiServiceGenerator and returns FAKE_USERS as a list.
    }

    /**
     * Generate a random {@link User} and add it {@link FakeApiService#users} list.
     * This user must be get from the {@link FakeApiServiceGenerator#FAKE_USERS_RANDOM} list.
     */
    @Override
    public void generateRandomUser() {
        // TODO: A modifier
        User newRandomUser = FakeApiServiceGenerator.FAKE_USERS_RANDOM.get(randomUser.nextInt(FAKE_USERS_RANDOM.size()));
        users.add(newRandomUser);
        // Implemented Random (line 13) to pick a random User from Api (FAKE_USERS_RANDOM).
    }

    /**
     * Delete a {@link User} from the {@link FakeApiService#users} list.
     */
    @Override
    public void deleteUser(User user) {
        // TODO: A modifier
        users.remove(user);
        // Used remove to delete user as User user is the parameter from the method.
    }
}
